### ISSUE TITLE
After Magento 2.4 Upgrade

### ISSUE THREAD

**Issue by MihaiTudorRO** [mageplaza/magento-2-better-popup#13]
`Compilation was started.
Interception cache generation... 6/8 [=====================>------]  75% 20 secs 434.0 MiBErrors during compilation:
        Mageplaza\BetterPopup\Plugin\Controller\Subscriber\NewAction
                Missed required argument subscriptionManager in parent::__construct call. File: /home/xxx/public_html/xxx/app/code/Mageplaza/BetterPopup/Plugin/Controller/Subscriber/NewAction.php
Total Errors Count: 1

In Log.php line 92:

  Error during compilation

setup:di:compile
`

**Comment by guilhermetb** [comment]
I have the same problem

**Comment by Tuvpt** [comment]
please refer this commit e2c7ff3c83a70cf685ee396526860b555f1f6a9c

**Comment by guilhermetb** [comment]
Thanks, you stopped giving an error during the deploy.
There are lines that you removed from the file that did not already exist in mine.
When I release the mouse from the page it opens the screen asking for the email to subscribe to the newsletter, but when I click send nothing happens.
