### ISSUE TITLE
popup.js hard-coded to email form field.

### ISSUE THREAD

**Issue by chazzs** [mageplaza/magento-2-better-popup#14]
the form submit function in popup.js is hard-coded to submit email input field and nothing else. yet the configuration allows for arbitrary form HTML but will never submit any form data other than a field with name "email"

should probably use Jquery serializeArray() function to submit all the form data, whatever it may be.

**Comment by Tuvpt** [comment]
Thank you for your feedback.
We highly appreciate any ideas, suggestions and comments like yours and consider them in our next improvement to make our products better. Thank you very much!
