### ISSUE TITLE
Issue while subscribing in magento 2.3.5-p2

### ISSUE THREAD

**Issue by manojiksula** [mageplaza/magento-2-better-popup#15]
1 exception(s):
Exception #0 (ReflectionException): Class Mageplaza\BetterPopup\Plugin\Controller\Subscriber\NewAction\Interceptor does not exist

Exception #0 (ReflectionException): Class Mageplaza\BetterPopup\Plugin\Controller\Subscriber\NewAction\Interceptor does not exist
<pre>#1 Magento\Framework\Code\Reader\ClassReader->getConstructor('Mageplaza\Better...') called at [vendor\magento\framework\ObjectManager\Definition\Runtime.php:54]
#2 Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Mageplaza\Better...') called at [vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php:48]
#3 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mageplaza\Better...') called at [vendor\magento\framework\ObjectManager\ObjectManager.php:70]
#4 Magento\Framework\ObjectManager\ObjectManager->get('Mageplaza\Better...') called at [vendor\magento\framework\Interception\PluginList\PluginList.php:250]
#5 Magento\Framework\Interception\PluginList\PluginList->getPlugin('Magento\Newslett...', 'betterpopup_ajax...') called at [vendor\magento\framework\Interception\Interceptor.php:133]
#6 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor\magento\framework\Interception\Interceptor.php:153]
#7 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('execute', array(), NULL) called at [generated\code\Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor.php:26]
#8 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->execute() called at [vendor\magento\framework\App\Action\Action.php:108]
#9 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#) called at [vendor\magento\framework\Interception\Interceptor.php:58]
#10 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#)) called at [vendor\magento\framework\Interception\Interceptor.php:138]
#11 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#) called at [vendor\magento\framework\Interception\Interceptor.php:153]
#12 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...', 'customer-segment...'))) called at [generated\code\Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor.php:39]
#13 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->dispatch(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#) called at [vendor\magento\framework\App\FrontController.php:162]
#14 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#, &Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor#00000000718f66d2000000003cd5a0b9#) called at [vendor\magento\framework\App\FrontController.php:98]
#15 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#) called at [vendor\magento\framework\Interception\Interceptor.php:58]
#16 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#)) called at [vendor\magento\framework\Interception\Interceptor.php:138]
#17 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#) called at [vendor\magento\module-store\App\FrontController\Plugin\RequestPreprocessor.php:99]
#18 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000718f64b3000000003cd5a0b9#, &Closure#00000000718f6428000000003cd5a0b9#, &Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#) called at [vendor\magento\framework\Interception\Interceptor.php:135]
#19 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#) called at [vendor\magento\module-page-cache\Model\App\FrontController\BuiltinPlugin.php:73]
#20 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000718f64b3000000003cd5a0b9#, &Closure#00000000718f6428000000003cd5a0b9#, &Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#) called at [vendor\magento\framework\Interception\Interceptor.php:135]
#21 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#) called at [vendor\magento\framework\Interception\Interceptor.php:153]
#22 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#), NULL) called at [generated\code\Magento\Framework\App\FrontController\Interceptor.php:26]
#23 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#00000000718f6503000000003cd5a0b9#) called at [vendor\magento\framework\App\Http.php:116]
#24 Magento\Framework\App\Http->launch() called at [generated\code\Magento\Framework\App\Http\Interceptor.php:24]
#25 Magento\Framework\App\Http\Interceptor->launch() called at [vendor\magento\framework\App\Bootstrap.php:261]
#26 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#00000000718f654f000000003cd5a0b9#) called at [index.php:39]
</pre>

**Comment by Uri-Mageplaza** [comment]
Thank you for contacting us!
We have received your notice and have fixed this issue.
Please refer this commit: e1b567f
