### ISSUE TITLE
Incompatibility with versions below 2.3.3

### ISSUE THREAD

**Issue by yuriy-boyko** [mageplaza/magento-2-better-popup#18]
With version 4.0.0 of the module, a new require-js was introduced:    jquery-ui-modules/widget
This library (jquery-ui-modules) was introduced only in magento 2.3.3 and you can find in /magento-dir/lib/web/jquery/ui-modules

so, the version 4.0.0 is incompatible with all magento versions below 2.3.3
Please fix this issue, or at lease warn users that the new version is not compatible anymore

**Comment by Uri-Mageplaza** [comment]
Hello,
I'm Uri from Mageplaza Support Team.

If you are using Magento 2.3.x versions, please try using the 2.3 version which is the appropriate version - [Better Popup 2.3](https://github.com/mageplaza/magento-2-better-popup/tree/2.3)
Version 4.0.0 is for Magento 2.4.x

Have a nice day!
