### ISSUE TITLE
Class 'Mageplaza\BetterPopup\Plugin\Controller\Subscriber\ObjectManager' not found

### ISSUE THREAD

**Issue by ghimiremanish** [mageplaza/magento-2-better-popup#20]
After installing the plugin I am getting this error.

Error: Class 'Mageplaza\BetterPopup\Plugin\Controller\Subscriber\ObjectManager' not found

**Comment by dotpreston** [comment]
I'm getting the same error when submitting the form

PHP Fatal error:  Uncaught Error: Class 'Mageplaza\\BetterPopup\\Plugin\\Controller\\Subscriber\\ObjectManager'

Not found in vendor/mageplaza/module-better-popup/Plugin/Controller/Subscriber/NewAction.php:55

**Comment by Tuvpt** [comment]
Thanks for the comments we have edited to fix this problem 30ae75aeac4dcfd35bf4a35a139fff4b9235e006
