### ISSUE TITLE
CSS error on magento 2.4.2

### ISSUE THREAD

**Issue by nix0x00** [mageplaza/magento-2-better-popup#23]
I installed this module on 2.4.2 but I am getting error and text/design cannot be seen. I have attached the screen shot, though I didn't get any error during installation.

Note: I installed it manually and executed following commands.

1. setup:upgrade
2. rm -rf generated/code/*
3. setup:di:compile
4. static-content:deploy -f
5. clear cache

**Comment by Tuvpt** [comment]
Please describe more about your problem. Steps for us to reproduce the problem.
Thank you!

**Comment by nix0x00** [comment]
@Tuvpt  Hi please follow the below steps to reproduce this error on Magento 2.4.2 with Php 7.4.x

1. wget https://github.com/mageplaza/magento-2-better-popup/archive/v4.0.0.zip
2. bin/magento setup:upgrade
3. rm -rf generated/code/* && rm -rf pub/static/*
4. bin/magento setup:di:compile
3. bin/magento setup:static-content:deploy en_US -f

then after enabling the module, I get following popup in the frontend. 

[](https://i.imgur.com/NhF7I0U.png)

**Comment by nix0x00** [comment]
> Please describe more about your problem. Steps for us to reproduce the problem.
> Thank you!

Still waiting for a reply.

**Comment by shashank141097** [comment]
@nix0x00 @Tuvpt are you guys got any solution to that issue?

**Comment by nix0x00** [comment]
> @nix0x00 @Tuvpt are you guys got any solution to that issue?

no, i just uninstalled

**Comment by KhietNguyen83** [comment]
Hi @nix0x00 ,
I'm Justin from Mageplaza.
Please download the latest version of BetterPopup module and test again.
Thank you!
