### ISSUE TITLE
Click outside the container to close the pop up

### ISSUE THREAD

**Issue by alonsoct00** [mageplaza/magento-2-better-popup#28]
How can I configure it so that it can be closed/hidden with a simple click outside the pop-up container?, like an ordinary modal, it is for UX purposes.

Thanks

**Comment by DHT-Uri** [comment]
Hello,

With the popup closing when clicking outside the popup. 
You can refer the following code with Jquery:

```
$(document).click(function (e)
{
    // The container contains the popup
    var container = $("selector_to_element_popup_wrapper");
 
    // If you click outside the container, hide it
    if (!container.is(e.target) && container.has(e.target).length === 0)
    {
        container.hide();
    }
});
```

Hope it will work for you.

**Comment by alonsoct00** [comment]
Ohh! thanks!! I will to tes this cc @hugomartinezpablo

**Comment by silversil** [comment]
> Hello,
> 
> With the popup closing when clicking outside the popup. You can refer the following code with Jquery:
> 
> ```
> $(document).click(function (e)
> {
>     // The container contains the popup
>     var container = $("selector_to_element_popup_wrapper");
>  
>     // If you click outside the container, hide it
>     if (!container.is(e.target) && container.has(e.target).length === 0)
>     {
>         container.hide();
>     }
> });
> ```
> 
> Hope it will work for you.

Sorry, could you please explain where I have to insert your code? Thank you in advance.
