### ISSUE TITLE
Activation: Email address is invalid.

### ISSUE THREAD

**Issue by p24-max** [mageplaza/magento-2-better-popup#34]
When trying to activate the module, error "Email address is invalid." is shown. But the email address entered is valid.

Magento 2.4.3-p1
Module version v4.1.3

**Comment by KhietNguyen83** [comment]
Hi @p24-max ,
I'm Justin from Mageplaza.
Please help me to download the latest version of Mageplaza_Core module and check again.
You can download here: https://github.com/mageplaza/module-core/tree/master
Thank you!
