### ISSUE TITLE
Class "Mageplaza\BetterPopup\Helper\Data" not found

### ISSUE THREAD

**Issue by inmediape** [mageplaza/magento-2-better-popup#35]
Class "Mageplaza\BetterPopup\Helper\Data" not found

How can fix it?

**Comment by inmediape** [comment]
We installed the module with composer. Data.php file exist in vendor/mageplaza/module-better-popup/Helper folder.

We have already run setup:upgrade and setup:di:compile. We also have composer remove and again composer require

**Comment by KhietNguyen83** [comment]
Regarding this issue, please download the extension directly from our site https://www.mageplaza.com/magento-2-better-popup/ along with the support package for further inspections and technical support. Thanks a lot!
