### ISSUE TITLE
Clicking outside of popup does not close it

### ISSUE THREAD

**Issue by DePalmo** [mageplaza/magento-2-better-popup#4]
Hello,

First I would like to thank you for the great and free extension! But I do have a request. Is it possible to upgrade it so that when user does click outside of the popup window, that it closes itself? Right now user needs to click on close button to do that.

**Comment by DePalmo** [comment]
FYI; I have updated `view\frontend\web\js\popup::_clickClose()` to this:
```
_clickClose: function () {
            $('#bio_ep_close, #bio_ep_bg').click(function () {
                $('#bio_ep').hide();
                $('#bio_ep_bg').hide();
                $('.btn-copy').text('Copy');
                $('canvas#screen').hide();
            });
        },
```

Now if I click on background, the popup closes. Would you consider adding this feature into your next release? If you'd like, you can also extend it, so that we can enable/disable it from admin.

**Comment by saunptit97** [comment]
Hi DePalmo!
I'm Roger from Mageplaza. I will surely note it to our developer to consider about developing it in the future. Thank you very much for your feedback.

**Comment by Tuvpt** [comment]
Close due to no response within 7 days.
