### ISSUE TITLE
Show popup only to selected user groups

### ISSUE THREAD

**Issue by DePalmo** [mageplaza/magento-2-better-popup#5]
Hello,

Is it possible to show the popup only to selected user groups? Like non-logged in or the ones that didn't sign up for newsletter yet?

**Comment by saunptit97** [comment]
Hi DePalmo!
I'm Roger from Mageplaza. Thank for your contacting.
Unfortunately, the current version has not supported this function yet. I'm so sorry about that. However, I will surely note it to our developer to consider about developing it in the future so please look forward to this. Thank you very much for your feedback.

**Comment by Tuvpt** [comment]
Close due to no response within 7 days.

**Comment by DePalmo** [comment]
Would appreciate if you kept this one and #4 open or at least provide some feedback once those two are done or won't be done. Thanks!
